# Every field must be added to the multiloader-common.gradle expandProps map.

# Common
java_version = 21
mod_version = 1.3.4
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Cobweb
mod_id = cobweb
mod_id_kebab = cobweb
license = CNCLv1
description = Crystal Nest API
credits =
github_user = crystal-nest
curseforge_id = 968456
minecraft_version = 1.21.11
# https://minecraft.wiki/w/Pack_format#List_of_data_pack_formats
pack_format = 94.1
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft = 1.21.10
parchment_version = 2025.10.12
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.11-20251209.172050

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.140.0+1.21.11
fabric_loader_version = 0.18.3

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 21.11.12-beta
neoforge_loader_version_range = [21.11,)

# Dependencies
fcap_version = 21.11.0

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
