name: Release Workflow

on:
  workflow_dispatch:
     inputs:
      version:
        type: string
        description: Version number
        required: true   

jobs:
  call-analyze-workflow:
    uses: crystal-nest/.github/.github/workflows/analyze.yml@main
    secrets: inherit 
  call-version-update-workflow:
    needs: call-analyze-workflow
    permissions: 
      contents: write
    uses: crystal-nest/.github/.github/workflows/version_update.yml@main
    with:
      version: ${{ github.event.inputs.version }}
    secrets: inherit
  call-release-workflow:
    needs: [call-analyze-workflow, call-version-update-workflow]
    permissions: 
      contents: write
    uses: crystal-nest/.github/.github/workflows/single_release.yml@main
    with:
      loader_forge: true
      loader_fabric: true
      loader_neoforge: false
      loader_common: true
      platform_maven: true
      platform_github: true
      platform_curseforge: true
      platform_modrinth: true
    secrets: inherit
